import { Conversation, ChatMessage } from '@/types';

export const mockConversations: Conversation[] = [
  {
    id: '1',
    patientId: 'p1',
    patientName: 'Maria Silva',
    initials: 'MS',
    avatarColor: 'green',
    lastMessage: 'Oi, Gostaria de saber os horários...',
    lastMessageTime: '10:30',
    status: 'bot_active',
    hasNotification: false,
    tenantId: 'tenant1',
    updatedAt: new Date('2026-05-22T10:30:00'),
  },
  {
    id: '2',
    patientId: 'p2',
    patientName: 'João Oliveira',
    initials: 'JO',
    avatarColor: 'orange',
    lastMessage: 'Oi, obrigado! Qual o valor da...',
    lastMessageTime: '10:25',
    status: 'waiting',
    hasNotification: false,
    tenantId: 'tenant1',
    updatedAt: new Date('2026-05-22T10:25:00'),
  },
  {
    id: '3',
    patientId: 'p3',
    patientName: 'Ana Costa',
    initials: 'AC',
    avatarColor: 'red',
    lastMessage: 'Estou com muita dor e preciso...',
    lastMessageTime: '10:20',
    status: 'requires_human',
    hasNotification: true,
    notificationCount: 1,
    tenantId: 'tenant1',
    updatedAt: new Date('2026-05-22T10:20:00'),
  },
  {
    id: '4',
    patientId: 'p4',
    patientName: 'Pedro Carvalho',
    initials: 'PC',
    avatarColor: 'purple',
    lastMessage: 'Gostaria de reagendar minha consulta',
    lastMessageTime: '09:15',
    status: 'bot_active',
    hasNotification: false,
    tenantId: 'tenant1',
    updatedAt: new Date('2026-05-22T09:15:00'),
  },
  {
    id: '5',
    patientId: 'p5',
    patientName: 'Lucas Santos',
    initials: 'LS',
    avatarColor: 'blue',
    lastMessage: 'Onde fica a clínica?',
    lastMessageTime: 'Ontem',
    status: 'bot_active',
    hasNotification: false,
    tenantId: 'tenant1',
    updatedAt: new Date('2026-05-21T18:00:00'),
  },
  {
    id: '6',
    patientId: 'p6',
    patientName: 'Carla Mendes',
    initials: 'CM',
    avatarColor: 'green',
    lastMessage: 'Preciso cancelar meu agendamento',
    lastMessageTime: 'Ontem',
    status: 'completed',
    hasNotification: false,
    tenantId: 'tenant1',
    updatedAt: new Date('2026-05-21T16:30:00'),
  },
];

// Mock messages for conversation with Ana Costa (requires_human)
export const mockMessages: Record<string, ChatMessage[]> = {
  '3': [
    {
      id: 'm1',
      conversationId: '3',
      sender: 'patient',
      senderName: 'Ana Costa',
      type: 'text',
      content: 'Estou com muita dor e preciso de atendimento urgente. tem alguma emergência?',
      status: 'read',
      timestamp: new Date('2026-05-22T10:20:00'),
    },
    {
      id: 'm2',
      conversationId: '3',
      sender: 'bot',
      type: 'text',
      content: 'Olá, Ana! Sinto muito que não esteja se sentindo bem. Para casos de emergência, recomendamos que procure o pronto atendimento mais próximo ou ligue para o 192.\n\nPosso ajudar com agendamento de consultas ou outras informações?',
      status: 'read',
      timestamp: new Date('2026-05-22T10:21:00'),
    },
    {
      id: 'm3',
      conversationId: '3',
      sender: 'patient',
      type: 'text',
      content: 'Não, preciso ser atendida hoje! A dor está muito forte!',
      status: 'read',
      timestamp: new Date('2026-05-22T10:22:00'),
    },
  ],
};

